### ISSUE TITLE
some typos at line 54, 128

### ISSUE THREAD

**Issue by RohitKS7** [PatrickAlphaC/ethers-simple-storage-fcc#11]
I have seen some typos on line no. 54 and 128. So, I fixed it and created a pull request.
I'm so happy to contribute!

**Comment by hidekiriyuga** [comment]
'''
reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
'''
i got this erroe while connecting to ganache rpc server.
''' [solidity]
const provider = new ethers.providers.JsonRpcProvider(
    "http://127.0.0.1:7545"
  );
'''

**Comment by PatrickAlphaC** [comment]
Thank you!
