### ISSUE TITLE
Getting error(estimateGas) while deploying contract

### ISSUE THREAD

**Issue by AmanSingh494** [PatrickAlphaC/ethers-simple-storage-fcc#111]
When I used the command 
`Node deploy.js`
It is giving the following error:
`Error: missing revert data (action="estimateGas", data=null, reason=null,
invocation: null,
  revert: null,
  shortMessage: 'missing revert data',
  info: {
    error: {
      message: 'VM Exception while processing transaction: invalid opcode',
      stack: 'RuntimeError: VM Exception while processing transaction: invalid opcode\n' +
        '    at exactimate (C:\\Program Files\\WindowsApps\\GanacheUI_2.7.1.0_x64__rb4352f0jd4m2\\app\\resources\\static\\node\\node_modules\\ganache\\dist\\node\\1.js:2:182136)',
      code: -32000,
      name: 'RuntimeError',
      data: [Object]
    },
    payload: {
      method: 'eth_estimateGas',
      params: [Array],
      id: 3,
      jsonrpc: '2.0'
    }
  }
}`
The package.json file
`{
  "name": "my-project",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "ethers": "^6.10.0",
    "solc": "^0.8.23-fixed"
  },
  "scripts": {
    "compile": "yarn solcjs --bin --abi --include-path node_modules/ --base-path , -o , SimpleStorage.sol"
  }
}`

deploy.js
`import { ethers } from 'ethers'
import * as fs from 'fs'
const main = async () => {
  //private key -0x10a8a8f5bc4953cd48356d82cb60a0a03ad916e5c07470663bd7ed1778294279 from ganache
  // rpc server - http://127.0.0.1:7545
  const provider = new ethers.JsonRpcProvider('http://127.0.0.1:7545') //this line connects to the blockchain //use this syntax for ethers version 6 and above
  const wallet = new ethers.Wallet(
    '0x10a8a8f5bc4953cd48356d82cb60a0a03ad916e5c07470663bd7ed1778294279',
    provider
  ) //this line gives a wallet with a private key

  // to deploy our contract we will need the abi and the binary compiled code of the contract.
  const abi = fs.readFileSync(
    './,/___SimpleStorage_sol_SimpleStorage.abi',
    'utf8'
  )
  const binary = fs.readFileSync(
    './,/___SimpleStorage_sol_SimpleStorage.bin',
    'utf8'
  )
  const contractFactory = new ethers.ContractFactory(abi, binary, wallet)
  console.log('Deploying Contract...')
  const contract = await contractFactory.deploy()
  console.log(contract)
}
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })`

SimpleStorage.sol

`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract SimpleStorage {
    uint256 favoriteNumber;

    struct People {
        uint256 favoriteNumber;
        string name;
    }
    People[] public people;

    mapping(string => uint256) public nameToFavoriteNumber;

    function store(uint256 _favoriteNumber) public {
        favoriteNumber = _favoriteNumber;
    }

    function retrieve() public view returns (uint256) {
        return favoriteNumber;
    }

    function addPerson(string memory _name, uint256 _favoriteNumber) public {
        people.push(People({favoriteNumber: _favoriteNumber, name: _name}));
        nameToFavoriteNumber[_name] = _favoriteNumber;
    }
}
`
Stuck on this, Please provide a solution.

**Comment by ghaouachi335** [comment]
I have the same erro, 3 day i am trying to fix it, i have even change from window to linux to fix it, i have even try to deploy it on sepolia with a metamask wallet, but nothing work

**Comment by AmanSingh494** [comment]
One more thing to add is that the contract was successfully deployed in remix Vm London at compiler version 0.8.19 but was not deployed at compiler version 0.8.23(the latest version).

**Comment by ghaouachi335** [comment]
yes, that's what i was suspected. i think the "solc": "^0.8.23-fixed" is the problem. i will try to fin an other way to download an lower version.

**Comment by AmanSingh494** [comment]
> yes, that's what i was suspected. i think the "solc": "^0.8.23-fixed" is the problem. i will try to fin an other way to download an lower version.

Yeah, I tried with Solc 0.8.19 but it still didn't work. Now I am going to look at the documentation.

**Comment by avi94** [comment]
Same for me. Guys let us know if it gets fixed and how it gets fixed. Meanwhile I will look into docs as well.

**Comment by ramziosta** [comment]
I am having a similar issue where it goes to Ganache but in the terminal, I don't get the same conformations as the video. [https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/6401](url)

**Comment by rocco1226** [comment]
Yes, I have the similar error: transaction underpriced, but the gasLimit and gasPrice are all the same to what ganache showed. And I dont know how to fix it.

**Comment by PatrickAlphaC** [comment]
Hmm... to be honest, I'd recommend running this with a hardhat node instead of ganache. Ganache has been discontinued

**Comment by sandrasong** [comment]
I fixed this error by 

1. Uninstall solc, then reinstall solc@0.8.7-fixed. 
2. Deleting both abi & bin files from your directory.
3. Recompile the contract to generate abi & bin files.

**Comment by AmanSingh494** [comment]
> Hmm... to be honest, I'd recommend running this with a hardhat node instead of ganache. Ganache has been discontinued

As Patrick has suggested, I used hardhat with Alchemy and I was able to deploy my contract to the Sepolia testnet. So leave ganache it seems to be incompatible now. Heartful thanks to Patrick for still updating us about this course.

**Comment by yu1195174476** [comment]
> I fixed this error by
> 
>     1. Uninstall solc, then reinstall [solc@0.8.7-fixed](mailto:solc@0.8.7-fixed).
> 
>     2. Deleting both abi & bin files from your directory.
> 
>     3. Recompile the contract to generate abi & bin files.

I meet the same Error and this solution can be worked
