### ISSUE TITLE
bash: cd--: command not found

### ISSUE THREAD

**Issue by Maakai123** [PatrickAlphaC/ethers-simple-storage-fcc#12]
``` gitpod Terminal
gitpod /workspace/ethers-simple-storage-fcc (main) $ cd--
bash: cd--: command not found
gitpod /workspace/ethers-simple-storage-fcc (main) $ cd..
bash: cd..: command not found
gitpod /workspace/ethers-simple-storage-fcc (main) $ nkdir new_folder
bash: nkdir: command not found
gitpod /workspace/ethers-simple-storage-fcc (main) $ bash: cd--: command not found

```

I got the above in my gitpod when trying to set up and create folder
can any one help?

**Comment by NnajiChimuanya** [comment]
It should be     mkdir new_folder      not nkdir new_folder

replace the n in nkdir with m

mkdir stands for make directory

**Comment by NnajiChimuanya** [comment]
It should be ` mkdir new_folder` not` nkdir new_folder`

replace the n in nkdir with m

`mkdir` stands for **make directory**

**Comment by PatrickAlphaC** [comment]
Closing issue, thanks @NnajiChimuanya!
