### ISSUE TITLE
Issue : could not detect network with ganache

### ISSUE THREAD

**Issue by ChadiZarkal** [PatrickAlphaC/ethers-simple-storage-fcc#17]
Hi all ! 
So I was trying to launch my first blockchain with ganache (hour 7) and I am stuck with the following issue : 
"reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
"

I made sure ganache is running, that I have ethers and fs 
I don't know where exactly the issue is so I can't make a minimalist code 

``` solidity

async function main() {
  const provider = new ethers.providers.JsonRpcProvider(
    "http://127.0.0.1:7545"
  );
  const wallet = new ethers.Wallet(
    "1b8975f86182691cc7a416ed4b6bc04dfabff769922925632232636f5da1c1c4",
    provider
  );
  const abi = fs.readFileSync("./SimpleStorage_sol_SimpleStorage.abi", "utf8");
  const binary = fs.readFileSync(
    "./SimpleStorage_sol_SimpleStorage.bin",
    "utf8"
  );
  const contractFactory = new ethers.ContractFactory(abi, binary, wallet);
  console.log("deploying please wait...");
  const contract = await contractFactory.deploy();
  console.log(contract);
}
```

Thank you for your help

**Comment by SYEDKHUSHAL** [comment]
I solved it for me 

If you are using linux environment, 
then you just have to do :

"yarn add ganache"
 in your terminal

and after that run : node deploy.js

**Comment by ChadiZarkal** [comment]
Still same issue :/

**Comment by Izmanovich** [comment]
Hey mate! if you are using WSL, try this:

1. Open Ganache
2. Quick start
3. (Right-hand corner) Click the gear icon
4. Server tab
5. Hostname - Select the one called: Ethernet (WSL)

Remember to change the provider and the private key for the wallet.
I hope this helps!

**Comment by ChadiZarkal** [comment]
Hallelujah! thank you 
Do you mind explaining why it didn't work in the first place?
And what did we do exactly here?

**Comment by M-Marcel** [comment]
> yarn add ganache

This isn't working

**Comment by PatrickAlphaC** [comment]
Great work!!

**Comment by debangi** [comment]
> yarn add ganache

Thanks, that worked for me

**Comment by abccca** [comment]
Thanks.

**Comment by nitinaimshigh** [comment]
> Hey mate! if you are using WSL, try this:
> 
> 1. Open Ganache
> 2. Quick start
> 3. (Right-hand corner) Click the gear icon
> 4. Server tab
> 5. Hostname - Select the one called: Ethernet (WSL)
> 
> Remember to change the provider and the private key for the wallet. I hope this helps!

Thanks a lot. It worked
