### ISSUE TITLE
error Command "--base-path" not found.

### ISSUE THREAD

**Issue by samsheldin** [PatrickAlphaC/ethers-simple-storage-fcc#19]
Hi Fam.
 i am at 6:53:10 of the course 
 Iran this command 
 `
 yarn --solcjs --bin --abi --include-path node-modules/ --base-path . -o . SimpleStorage.sol`

and it shows an error 

```
error Command "--base-path" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Carrie004** [comment]
> Hi samsheldin, try running without yarn. Run following command: `solcjs --bin --include-path node_modules/ --base-path . MainContract.sol`

I also had the same problem. I tried you solution and now I have the following error. Do you may be know what is the problem?  ''' solidity ParserError: Found version pragma, but failed to parse it. Please ensure there is a trailing semicolon.
 --> SimpleStorage.sol:4:1:
  |
4 | pragma solidity 0.8.7-fixed;
'''

**Comment by PatrickAlphaC** [comment]
Use:

```
pragma solidity 0.8.7;
```

Not:

```
pragma solidity 0.8.7-fixed;
```

**Comment by Carrie004** [comment]
Thanks. It works.
