### ISSUE TITLE
deploy.js is throwing a no network error 

### ISSUE THREAD

**Issue by Aditya227173** [PatrickAlphaC/ethers-simple-storage-fcc#2]
I am at 7:07:38 in the course where Patrick first runs the deploy.js using the command node deploy.js. Instead of getting the contract details, it throws an error stating "**could not detect network**". Any help would be much appreciated.
the entire error is as follows:

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (/home/bondiver/hh-fcc/ethers-ss/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/bondiver/hh-fcc/ethers-ss/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at JsonRpcProvider.<anonymous> (/home/bondiver/hh-fcc/ethers-ss/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:561:54)
    at step (/home/bondiver/hh-fcc/ethers-ss/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/bondiver/hh-fcc/ethers-ss/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/bondiver/hh-fcc/ethers-ss/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

Below is my deploy.js code,

``` javascript
const ethers = require("ethers");
const fs = require("fs-extra");

async function main() {
  // http://127.0.0.1:7545

  const provider = new ethers.providers.JsonRpcProvider(
    "HTTP://127.0.0.1:7545"
  );
  const wallet = new ethers.Wallet(
    "6e6170240a5a4462244c76841fbaac9fe4edd90af97e44574647c5bc0db11197",
    provider
  );

  const abi = fs.readFileSync("./SimpleStorage_sol_SimpleStorage.abi", "utf8");
  const binary = fs.readFileSync(
    "./SimpleStorage_sol_SimpleStorage.bin",
    "utf8"
  );
  const contractFactory = new ethers.ContractFactory(abi, binary, wallet);
  console.log("deployment in process...");
  const contract = await contractFactory.deploy();
  console.log(contract);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

**Comment by deepakdubey8756** [comment]
Check whether your ganache RPC server is running or not. Everything else seems correct.

**Comment by Aditya227173** [comment]
> Check whether your ganache RPC server is running or not. Everything else seems correct.

I did check it, I have tried restarting ganache and VS code, but it does not seem to resolve the problem. I did update the private key after restarting ganache, although I don't think that is relevant to the network issue.

**Comment by deepakdubey8756** [comment]
Possible Solutions may be:
1. Check whether your ganache is running on localhost:8545 or localhost:7545. 
2.  Switch to different network and check whether it is running on different network or not.
3.  Try to connect with truffle. 
Same code worked for me correctly. So it is not code related issue.

**Comment by praneethwelideniya** [comment]
const provider = new ethers.providers.JsonRpcProvider(
    "HTTP://127.0.0.1:7545"
  );
Change above code as below and try
const provider = new ethers.providers.JsonRpcProvider(
    "http://127.0.0.1:7545"
  );

**Comment by Aditya227173** [comment]
It seems to have been a server issue, it would not work on my localhost but when I switched it to a wifi IP on ganache it finally worked.

**Comment by GeorgiNedyalkov** [comment]
Hi, I am having the same issue. Please excuse me If my questions are stupid but I am just starting out.

How can I see on which localhost is ganache running?
Here is the RPC server on Ganache app: HTTP://127.0.0.1:7545 

How did you switch to a wifi IP on ganache?

Thank you in advance!

**Comment by PatrickAlphaC** [comment]
Stupid questions are great!

**Comment by DeathDEMONA** [comment]
Hi! I have exactly same issue with Ganache (
Checked all possible networks (localhost, wifi, vEthernet), but still getting:

`Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)`

Found in internet that something in Windows can block non-SSL requests. But even with switched off firewall, I still cannot deploy a contract. Trying to fix this issue for 3 days without success.

**Comment by PatrickAlphaC** [comment]
Any of these help? 

https://github.com/smartcontractkit/full-blockchain-solidity-course-js/blob/main/chronological-updates.md#windows-wsl--ganache

**Comment by PatrickAlphaC** [comment]
Just do that for now, we used ganache as a stepping stone to running from the command line anyways.
