### ISSUE TITLE
Cant deploy contract to test network. 

### ISSUE THREAD

**Issue by cah311** [PatrickAlphaC/ethers-simple-storage-fcc#21]
In section 5 I am right at the part at the very end where I am trying to deploy the contract to the test netwrok and I am getting this error: 

Deploying, please wait...
<ref *1> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error",

It deployed just fine when connecting to ganache. The video also never mentioned anything about inputting a gas fee at this point either

**Comment by PatrickAlphaC** [comment]
Can you add:

1. Your contract code 
2. Your deploy code
3. Make sure your account has testnet ETH in it

Please format with 3 backticks and the word javascript
Like so:
```
```javascript
```
```
