### ISSUE TITLE
ENV Variable not able to read on terminal

### ISSUE THREAD

**Issue by mertdeveci5** [PatrickAlphaC/ethers-simple-storage-fcc#28]
Hey there - so when I try to run the deploy.js script with encrypted keys, I try to set the environment variable for PRIVATE_KEY_PASSWORD=PASSWORD in the terminal.  For your information, I did not install all the Ubuntu environment for coding hence the terminal I use is still with Windows. I think the problem is that I cannot find anywhere how to pass a "node deploy.js" command with a ENV variable set in the terminal in Windows. Could you help? 

![image](https://user-images.githubusercontent.com/83559696/178599061-1f887d2b-b6db-4234-b64a-3bab9a0cce35.png)

**Comment by PatrickAlphaC** [comment]
Environment variables in windows are much tricker. You're going to have a hard time if you try to do the whole course in a windows environment. 

https://www.minitool.com/news/environment-variables-windows-10-005.html

Please see this link to learn more. Closing this as it's not an issue. Please use the full repo discussions tab for more questions. Thanks. 

https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
