### ISSUE TITLE
 deploy.js wont deploy. 

### ISSUE THREAD

**Issue by prInce0712** [PatrickAlphaC/ethers-simple-storage-fcc#29]
I am in the part where we added the dependencies. see code below. 

![error123](https://user-images.githubusercontent.com/76728318/179389022-238bf6b8-6814-4b56-80d9-aff2cf42befa.png)

but I am getting this error when I run node
![error1234](https://user-images.githubusercontent.com/76728318/179389053-1805383a-750a-46d6-a0f8-8c5fce9ffc61.png)
 deploy.js , anyone knows what is going on here?

**Comment by kevinabraham23** [comment]
if ur using wsl ubuntu on a windows system it wont work
https://github.com/smartcontractkit/full-blockchain-solidity-course-js/blob/main/chronological-updates.md#using-the-wsl-endpoint
just go to this link and try any one of these steps and u should be fine :)

**Comment by prInce0712** [comment]
> if ur using wsl ubuntu on a windows system it wont work https://github.com/smartcontractkit/full-blockchain-solidity-course-js/blob/main/chronological-updates.md#using-the-wsl-endpoint just go to this link and try any one of these steps and u should be fine :)

THANK YOU SO MUCH, I've been stuck for this issue for days.. I can continue now with the tutorial.. thank you again..

**Comment by prInce0712** [comment]
thanks

**Comment by ElmeriVincent** [comment]
> if ur using wsl ubuntu on a windows system it wont work https://github.com/smartcontractkit/full-blockchain-solidity-course-js/blob/main/chronological-updates.md#using-the-wsl-endpoint just go to this link and try any one of these steps and u should be fine :)

I forgot I had doublevpn on... changed it to a basic vpn connection and did what you said and it started working, cheers!

**Comment by lumiroy** [comment]
My setup: VS Code running remote on WSL2 Ubuntu. Using ganache on Windows wouldn't play at all with ethers.js on WSL2.
yarn add did not work for me either. Finally got it installed & working using npm.

This is what finally worked:

```
npm i -g ganache
ganache
<A bunch of stuff displays when it starts. Match JSON-RPC url (127.0.0.1:8545) & private key in code>
<keep ganache running and open new terminal>
node deploy.js
```
