### ISSUE TITLE
Error: invalid hexlify value

### ISSUE THREAD

**Issue by shakilkhan12** [PatrickAlphaC/ethers-simple-storage-fcc#30]
![error](https://user-images.githubusercontent.com/10473411/180435985-4052470f-95cf-4f79-ad5d-aad26b39c367.PNG)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
