### ISSUE TITLE
yarn.lock,node_modules and package.jason is not coming

### ISSUE THREAD

**Issue by muhdalik** [PatrickAlphaC/ethers-simple-storage-fcc#34]
After running the yarn add solc, yarn.lock,node_modules and package.jason is not generating on file side in vs code.
![image](https://user-images.githubusercontent.com/25792513/182989487-8539815e-ac3a-4966-8b90-86594deb5888.png)

**Comment by muhdalik** [comment]
Can someone help me please?

**Comment by zen0net** [comment]
Same problem here. 
You solved it?

**Comment by muhdalik** [comment]
> Same problem here. You solved it?

Not yet.

**Comment by PatrickAlphaC** [comment]
This has been answered here: https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/45

and here: https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/579

You likely have a yarn.lock, package.json, or node_modules in a parent folder.

Please use the full repo for further questions with the course, thank you.
