### ISSUE TITLE
Error running node deploy.js command in the terminal - Error: Cannot find module

### ISSUE THREAD

**Issue by surfnparmy** [PatrickAlphaC/ethers-simple-storage-fcc#38]
I'm just at the start (6:35:00) of using VSC and can't find a solution. I've tried reinstalling, and restarting, won't work!

When I try to run the deploy.js code using
`node deploy.js`
in the terminal, I get the following error:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/surfnparmy/folder/test.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I found this on Github but didn't seem like there was a single solution. Most didn't make sense :/ 
https://github.com/nodejs/help/issues/3709

What it looks like for me:
![image](https://user-images.githubusercontent.com/110748572/188592846-9250d5cb-11bf-432b-b167-3dc1c1c2756a.png)

Please help!

**Comment by surfnparmy** [comment]
Thanks Mahmoud, I have it working now! There were a few extra steps I'll document below for anyone else having this problem.

When I ran npm install command I received the below:

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/surfnparmy/folder/hh-fcc/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/surfnparmy/folder/hh-fcc/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/surfnparmy/.npm/_logs/2022-09-08T22_48_55_254Z-debug-0.log
```

After looking into ENOENT error, I found this article and completed the following: https://sebhastian.com/npm-err-enoent/

```
# 👇 update npm to the latest version
npm install -g npm@latest

# 👇 clean npm cache
npm cache clean --force

# 👇 delete node modules and package-lock.json 
npm rm -rf node_modules && rm package-lock.json

# 👇 retry installing dependencies
npm install
```

npm install now appears to work, but I'm still getting this error:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/surfnparmy/folder/hh-fcc/deploy.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I then found that I'd created an extra folder in my directy, which meant the path was incorrect. 

Once I moved the test.js file up into the hh-fcc folder (see first screenshot) the path was correct and the console.log function printed 'Hi' in the terminal. 

You can check the path by right-clicking on files/folders in the explorer.

Hope this helps someone else!

**Comment by MahmoudMardawi** [comment]
I still have my problem. I think it's from the recourse
If you like to see what I'm facing please clone the following project. then install npm modules, then run this command in vscode : "npm run dev" 
https://github.com/wbkd/webpack-starter

**Comment by MahmoudMardawi** [comment]
I'm getting this error :
PS D:\Downloads\JS\webpack-starter> npm run dev

> webpack-starter@1.0.0 dev
> node index.js

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'D:\Downloads\JS\webpack-starter\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
