### ISSUE TITLE
In package.json -> scripts -> compile 'yarn' is redundant and causes the compilation to run twice

### ISSUE THREAD

**Issue by kadza** [PatrickAlphaC/ethers-simple-storage-fcc#39]
As stated in the description. 

Please, take a look at the terminal: https://www.youtube.com/watch?v=gyMwXuJrbJQ&t=23398s

**Comment by PatrickAlphaC** [comment]
Fixed in e2a3a54dc59c7e75a1e26a28d0053a41fa151f04
