### ISSUE TITLE
ts-node command not found

### ISSUE THREAD

**Issue by technophile-04** [PatrickAlphaC/ethers-simple-storage-fcc#4]
If we don't have ts-node installed globally its gives the error ts-node command not found. Need to update README.MD to use `npx ts-node deploy.ts` if using npm  or `yarn ts-node deploy.ts` for yarn.

**Comment by technophile-04** [comment]
created the pull request for same

**Comment by t3reetan** [comment]
You could alternatively also do `yarn ts-node deploy.ts` since we're using the yarn package manager in this course.

**Comment by TechnoRahmon** [comment]
try to install the **ts-node** globally in your system, I tried it and this worked for me.

I installed: ts-node and typescript like this: 

`npm i -g ts-node`
`npm i -g typescript`

then try the ts-node version to be sure that it is installed correctly : 
`ts-node --version`

**Comment by technophile-04** [comment]
Thanks all for the help 🙌, closing it since PR #5  for this is already is merged
