### ISSUE TITLE
Ganache doesn't start RPC  server

### ISSUE THREAD

**Issue by EgyptianM** [PatrickAlphaC/ethers-simple-storage-fcc#47]
When I launch Ganache it shows this screen and doesn't start the server

![image](https://user-images.githubusercontent.com/12565380/194920231-e119e9a5-a963-4ce8-a284-bf97617c2c0c.png)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by EgyptianM** [comment]
> Can you:
> 
> 1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
> 2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

Yes sure I'll post it as a discussion.
And for No. 2 there code or error msg related to the issue
It was working fine, I just restarted my PC and it stopped working anymore.
