### ISSUE TITLE
Code works without transactionResponse.wait() using Ganache, but doesn't work on real testnet without it.

### ISSUE THREAD

**Issue by babelpainterwell** [PatrickAlphaC/ethers-simple-storage-fcc#57]
<img width="806" alt="Screen Shot 2022-12-29 at 10 50 05 AM" src="https://user-images.githubusercontent.com/113453534/209977273-47da38c1-1d57-4688-ba3a-e3961cb55396.png">

'''  const currentFavNum = await contract.retrieve();
    console.log(`Current favorite number is: ${currentFavNum}`);
    console.log("Updating favorite number...");
    let transactionResponse = await contract.store(7);
    // let transactionReceipt = await transactionResponse.wait();

    const updatedFavNum = await contract.retrieve();
    console.log(`Updated favorite number is: ${updatedFavNum}`);'''

As the screenshot shows, the favNum is not updated if I comment out the '''transactionResponse.wait()''', but then it works perfectly when I add it back. Wondering why? 

ps: it only happens when I'm using Goerli. Ganache works fine with or without '''transactionResponse.wait()'''

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
