### ISSUE TITLE
EncryptedKey and Password not working

### ISSUE THREAD

**Issue by Micky447** [PatrickAlphaC/ethers-simple-storage-fcc#59]
When I am trying to deploy contract with password it is show no commend found error 
"PRIVATE_KEY_PASSWORD=SAYA123 : The term 'PRIVATE_KEY_PASSWORD=SAYA123' is not 
recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again."
and also if i tryin to delete PRIVATE_KEY from .env it is also not working.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
