### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'wait')

### ISSUE THREAD

**Issue by cryptocambi** [PatrickAlphaC/ethers-simple-storage-fcc#70]
Hi,

I am deploying the following part of the exercise:

const transactionResponse = await contract.store("7");
  const transactionReceipt = await contract.transactionResponse.wait(1);
  const updatedFavoriteNumber = await contract.retrieve();
  console.log(`Update favorite number: ${updatedFavoriteNumber}`);

but for what I can understand, it saying that is not able to  read the wait property, since the transactionResponse const is of type undefined:

PS C:\Users\K\hh-fcc\ethers-simple-storage> node deploy.js
Deploying please wait.....
Current favorite number: 0
TypeError: Cannot read properties of undefined (reading 'wait')
    at main (C:\Users\K\hh-fcc\ethers-simple-storage\deploy.js:29:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 

Any help please, the only thing I can think is to include the property on json file, but I don't if is correct and if is correct I don't know how to do it.

Any help is welcome

Thank

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
