### ISSUE TITLE
deploy error with "ethers.providers.JsonRPCProvider is not a constructor "

### ISSUE THREAD

**Issue by malommey** [PatrickAlphaC/ethers-simple-storage-fcc#79]
i have installed ether 5.7.0 plus deleting the node modules and reinstalling ethers. i have also change my ganache RPC server to wifi. i also run ganache on terminal WSL buts till. i got this error "ethers.providers.JsonRPCProvider is not a constructor "

sync function main(){
    const provider = new ethers.providers.JsonRPCProvider("http://127.0.0.1:8545");

please help i cant deploy my contract

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by malommey** [comment]
Sorry for Stressing you. its on  discussion full repo now. thank you sir
