### ISSUE TITLE
Err while running simplestorage contract with ethers....

### ISSUE THREAD

**Issue by Gok26** [PatrickAlphaC/ethers-simple-storage-fcc#83]
```
TypeError: no matching function (argument="key", value="deployTransaction", code=INVALID_ARGUMENT
, version=6.4.2)

```

Got this error while running the simplestorage contract using ethers, Could any one help me with on what's going wrong?

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
