### ISSUE TITLE
Error: could not coalesce error

### ISSUE THREAD

**Issue by mashukur-rahman** [PatrickAlphaC/ethers-simple-storage-fcc#92]
When I am trying to deploy my smart contract it is being deployed but Then I am getting this error and "store" or "retrieve" function is not working.

_`Error: could not coalesce error (error={ "code": -32000, "data": { "hash": "0x875771d7b9bca6b9eb90b0c6c802740ee1b8fda2b11255e6095b45787c7733cd", "message": "inva
lid opcode", "programCounter": 24, "reason": null, "result": "0x875771d7b9bca6b9eb90b0c6c802740ee1b8fda2b11255e6095b45787c7733cd" }, "message": "VM Exception whi
le processing transaction: invalid opcode", "name": "RuntimeError", "stack": "RuntimeError: VM Exception while processing transaction: invalid opcode\n    at EIP
1559FeeMarketTransaction.fillFromResult`_

I am using ^0.8.19 for both Solidity and solc. My code is directly copied from the course repository and I have replaced it with my private key and rpc.

**Comment by mashukur-rahman** [comment]
@PatrickAlphaC  could you please look into this?

**Comment by mashukur-rahman** [comment]
The problem was with the version of solc. I downgraded it to 0.7.5 and it works perfectly.

**Comment by ThomasCode92** [comment]
Fixed it for me also, but why was it not working with version 0.8.19?
